-- MySQL Script generated by MySQL Workbench
-- Thu May 14 21:59:26 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_musicalverse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_musicalverse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_musicalverse` DEFAULT CHARACTER SET utf8 ;
USE `bd_musicalverse` ;

-- -----------------------------------------------------
-- Table `bd_musicalverse`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_musicalverse`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `pontos` INT NULL DEFAULT 0,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;

select * from usuario;


-- -----------------------------------------------------
-- Table `bd_musicalverse`.`musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_musicalverse`.`musical` (
  `id_musical` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `data_criacao` DATE NULL,
  `data_estreia` VARCHAR(45) NULL,
  `base` VARCHAR(50) NULL,
  `musicalcol` VARCHAR(45) NULL,
  PRIMARY KEY (`id_musical`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_musicalverse`.`comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_musicalverse`.`comentario` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(30) NULL,
  `conteudo` TEXT NULL,
  `comentario_id_comentario` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `fk_comentario_comentario1_idx` (`comentario_id_comentario` ASC) VISIBLE,
  INDEX `fk_comentario_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_comentario_comentario1`
    FOREIGN KEY (`comentario_id_comentario`)
    REFERENCES `bd_musicalverse`.`comentario` (`id_comentario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentario_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `bd_musicalverse`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_musicalverse`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_musicalverse`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_musicalverse`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_musicalverse`.`avaliacao` (
  `usuario_id_usuario` INT NOT NULL,
  `musical_id_musical` INT NOT NULL,
  `nota` INT NOT NULL,
  `data_avaliacao` DATE NULL,
  `id_avaliacao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `musical_id_musical`),
  INDEX `fk_avaliacao_usuario1_idx` (`usuario_id_usuario` ASC) VISIBLE,
  INDEX `fk_avaliacao_musical1_idx` (`musical_id_musical` ASC) VISIBLE,
  CONSTRAINT `fk_avaliacao_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `bd_musicalverse`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_avaliacao_musical1`
    FOREIGN KEY (`musical_id_musical`)
    REFERENCES `bd_musicalverse`.`musical` (`id_musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_musicalverse`.`categoria_has_musical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_musicalverse`.`categoria_has_musical` (
  `categoria_id_categoria` INT NOT NULL,
  `musical_id_musical` INT NOT NULL,
  PRIMARY KEY (`categoria_id_categoria`, `musical_id_musical`),
  INDEX `fk_categoria_has_musical_musical1_idx` (`musical_id_musical` ASC) VISIBLE,
  INDEX `fk_categoria_has_musical_categoria1_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_categoria_has_musical_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `bd_musicalverse`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_has_musical_musical1`
    FOREIGN KEY (`musical_id_musical`)
    REFERENCES `bd_musicalverse`.`musical` (`id_musical`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
